<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageReadmeFile>README.md</PackageReadmeFile>


    <IsPackable>true</IsPackable>
    <PackageId>Rotbarsch.ReqnrollBindingMetadataExtractor</PackageId>
    <Description>Utilities for extracting metadata from Reqnroll bindings, including their comments.</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
